name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.*
    - name: Install dependencies
      run: dotnet restore Simple.Sqlite/Simple.Sqlite.csproj
    - name: Build
      run: dotnet build Simple.Sqlite/Simple.Sqlite.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test UnitTest/UnitTest.csproj --no-restore --verbosity normal
